# Generated by Django 5.0.6 on 2024-06-18 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ChoixLanguage',
            new_name='Message',
        ),
        migrations.RenameField(
            model_name='message',
            old_name='language',
            new_name='text',
        ),
    ]
