# Generated by Django 5.0.6 on 2024-06-22 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_questionresponse_delete_message_alter_article_title'),
    ]

    operations = [
        migrations.DeleteModel(
            name='QuestionResponse',
        ),
    ]
