# Generated by Django 5.0.6 on 2024-06-22 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_delete_questionresponse'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=250)),
                ('response', models.CharField(max_length=250)),
                ('lang', models.CharField(choices=[('fr', 'Français'), ('en', 'English')], max_length=2)),
            ],
        ),
    ]
